### PR TITLE
How to define a database

### PR DESCRIPTION
**Pull request by alevesely**
This may close the database issue

### CODE REVIEW

**Comment by szepeviktor** [comment]
~~Could you explain why is it Ok to install an inactive config file? `zdkimfilter.conf.dist`~~

Excuse me: https://github.com/szepeviktor/zdkimfilter/pull/10/files#diff-07e2cd25f7da0550504d107fb2cae5beR24

**Comment by szepeviktor** [comment]
I am a bit confused. Is there an inactive config file in /etc ?

**Comment by alevesely** [comment]
Having `zdkimfilter.conf.dist` installed there eases the creation of `zdkimfilter.conf` in the directory where it belongs.  If you change its location, you have to modify `postinst` accordingly.

**Comment by alevesely** [comment]
Inactive file?!

**Comment by szepeviktor** [comment]
> Inactive file?!

I think [zdkimfilter does not read](https://github.com/szepeviktor/zdkimfilter/blob/7f5c48b8ec7b09823390926f6fbea4163cf4aa93/src/parm.h#L34) `zdkimfilter.conf.dist`.

**Comment by szepeviktor** [comment]
> Having zdkimfilter.conf.dist installed there eases the creation of zdkimfilter.conf

I agree with that but Debian policy says example files live in another location.

Could we [activate it](https://github.com/szepeviktor/zdkimfilter/pull/10/files#diff-94c75624cc422098192120f0aa714a21L2) or move it to `/usr/share/...`?

**Comment by alevesely** [comment]
>> Having zdkimfilter.conf.dist installed there eases the creation of zdkimfilter.conf

> I agree with that but Debian policy says example files live in another location.

Hm... how about ```/etc/ca-certificates.conf.dpkg-old
/etc/gnome/defaults.list.dpkg-old
/etc/courier/courierd.dpkg-old
/etc/courier/authdaemonrc.dpkg-old ...```

> Could we activate it or move it to /usr/share/...?

Yeah, if you insist...

**Comment by szepeviktor** [comment]
`*.dpkg-old` is a backup file after a package update when you choose to use the *maintainer's verion*.

**Comment by szepeviktor** [comment]
> Could we activate it or move it to /usr/share/...?
> 
> Yeah, if you insist...

Thank you. Please decide on activating it or moving it to `/usr/share`.

**Comment by alevesely** [comment]
`/usr/share/zdkimfilter/zdkimfilter.conf.orig.dist`, which introduces one more coupling between `postinst` and `rules`.  That's by far not the worst hack in my PR.  There's coupling between scripts and pieces of `odbx_example`s.  I'll try and smooth them down in the next release.
However, next release will have to accommodate more database fields, which will complicate the upgrade process.  Until now, I managed that by summarizing database changes in the release notes and letting users manage that.  I'm not aware of anybody having followed that.  Anyway, debian upgrade process must do it without asking questions, and we'll have to work out how.  For sure, we'll have to rely on versioning to manage upgrades.  Hence, "1.6-1" sounds wrong if the next upstream release will be 1.6 _and_ will have additional fields/tables.
Do you know if anybody install those .deb packages?  The one I see is "1.5-4".

**Comment by szepeviktor** [comment]
> Do you know if anybody install those .deb packages?

Yes. Me.

**Comment by szepeviktor** [comment]
Thank you for your work.

**Pull request merged**
