### PR TITLE
Compiles on Trusty?

### PR DESCRIPTION
**Pull request by szepeviktor**
https://docs.travis-ci.com/user/trusty-ci-environment/#Using-the-Trusty-beta

### CODE REVIEW

**Comment by szepeviktor** [comment]
@alevesely Could you take a look at these:
https://travis-ci.org/szepeviktor/zdkimfilter/builds/102826827#L506

https://travis-ci.org/szepeviktor/zdkimfilter/builds/102826827#L735

**Comment by szepeviktor** [comment]
Maybe autoconf and automake-generated files should be removed from the source?

**Comment by alevesely** [comment]
@szepeviktor I never tried Trusty, but zdkimfilter should compile all right, as it has no special system requirements.  In fact, the tarball was probably done by automake/aclocal 1.11.6, but I had no problem building with 1.14.1.  The generated files allow to build the package without installing auto tools.  Otherwise, you may want to run autoreconf to generate them anew.

I fixed the warnings, but hold them for next release.  You may want to get a patch using `svn diff -r 139:140 http://www.tana.it/svn/zdkimfilter/trunk/src/dkimsign.c`

Configure assumes courier v. 60 if it cannot find `imapd`.  IMAP is not required by zdkimfilter, but that command accepts `--version`.  It shouldn't make much difference, so long as it's fairly recent.

Ale

**Comment by szepeviktor** [comment]
> Configure assumes courier v. 60 if it cannot find imapd. IMAP is not required by zdkimfilter, but that command accepts --version. It shouldn't make much difference, so long as it's fairly recent.

@alevesely Good news! `courier` also accepts --version, at least in v0.76.3

```
# on Debian
/usr/sbin/courier --version
Courier 0.76.3 Copyright 1999-2015 Double Precision, Inc.
```

**Comment by szepeviktor** [comment]
Also in earlier versions
```
/usr/sbin/courier --version
Courier 0.68.2 Copyright 1999-2012 Double Precision, Inc.
```

**Comment by alevesely** [comment]
Yes, version seems to be there since 2004-04-24 (0.45.5) according to ChangeLog.  IIRC, I used imapd because it is in path.  courier gets installed in /usr/sbin or /usr/local/sbin, which shouldn't be in path when configuring and compiling.

I agree trying one of the well known locations of the binary is better than guessing.  But then courier_version is only used to exclude the ugly hack, required for versions until 0.58.  Perhaps it's cleaner to get rid of all of that stuff than worsen it by adding an AC_PATH_PROG and parsing out the version if successful...   No?

**Comment by szepeviktor** [comment]
Probably, I was never a 0.58 user.

**Comment by szepeviktor** [comment]
Moved to svn files and debian packaging:
https://travis-ci.org/szepeviktor/zdkimfilter/builds/228053699

**Pull request closed without merging**
