### PR TITLE
Simplify ZLIB

### PR DESCRIPTION
**Pull request by szepeviktor**
@alevesely Would you mind simplifying ZLIB?
https://github.com/szepeviktor/zdkimfilter/pull/9/files

### CODE REVIEW

**Comment by alevesely** [comment]
Sorry I hadn't seen this before.  I must have written that `if` after getting discomforted by lots of useless `-I /usr/include`  resulting from the default behavior of [m4_ax_check_zlib](https://github.com/vysheng/tg/blob/master/m4_ax_check_zlib.m4):
```  
    #
    # If both library and header were found, action-if-found
    #
    m4_ifblank([$1],[
                CPPFLAGS="$CPPFLAGS -I${ZLIB_HOME}/include"
                LDFLAGS="$LDFLAGS -L${ZLIB_HOME}/lib"
                LIBS="-lz $LIBS"
                AC_DEFINE([HAVE_LIBZ], [1],
                          [Define to 1 if you have `z' library (-lz)])
               ],[
```
Is it worth filing a pull request there?  Hmm...  perhaps most users use [silent builds](https://autotools.io/automake/silent.html) or don't mind verbosity, so it wouldn't be worth.  But why would it be worth merging this patch in that case?

**Comment by szepeviktor** [comment]
This PR is for just showing the change.
Could you use the `AX_CHECK_ZLIB` macro?

**Comment by szepeviktor** [comment]
> Already in use.  I just supply $1.

Thanks.

**Comment by szepeviktor** [comment]
@alevesely Oh I see!

This PR is about to show that without `$1` is does the same. So you may skip it.

**Pull request closed without merging**
